### PR TITLE
Added the readmore functionality

### PR DESCRIPTION
**Pull request by master-wayne7**
### Description: 
In this PR I have addressed the issue of adding a feature of read more functionality in review text. I addressed it by adding a package `readmore`, and set the threshold to 3 lines. 
And I have also update the intl package to `1.19.0` as the pub was throwing an error of version miss match.

### CODE REVIEW

**Comment by Smuzzy-waiii** [comment]
LGTM for the most part. I was not able to build the app due to a version issue. Can you please change intl version to `intl: ^0.18.1` in pubspec.yaml

image

Also the read more and read less text have different colors (orange and black) Make them same color please. Also please leave a space bw the end of text and "Read less"

**Comment by master-wayne7** [comment]
@Smuzzy-waiii I have pushed one commit regarding the color and intl version

**Comment by Smuzzy-waiii** [comment]
image

image

Its still 2 colors. Sorry for the delay, was having dinner

**Comment by Smuzzy-waiii** [comment]
Feel free to leave that bug if you don't wanna. If you can get that fixed, I'll give 10 more

**Comment by Smuzzy-waiii** [comment]
@master-wayne7 Let me know if you want to fix the bug or leave it at this

**Comment by master-wayne7** [comment]
@Smuzzy-waiii can you describe a little bit what color should be applied and when ?

**Comment by Smuzzy-waiii** [comment]
LGTM Thanks!

**Comment by Smuzzy-waiii** [comment]
!bounty 10

**Comment by Smuzzy-waiii** [comment]
!bounty 55

**Pull request merged**
